=== Technology-Hatchery/restsql-test/src/resources/xml/service/testcase/ServiceTestCaseDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://restsql.org/schema" elementFormDefault="unqualified"
	xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tc="http://restsql.org/schema">

	<element name="testcase" type="tc:ServiceTestCaseDefinition"></element>

	<complexType name="ServiceTestCaseDefinition">
		<sequence>
			<element name="setup" type="tc:SetupOrTeardown" maxOccurs="1" minOccurs="0"></element>
			<element name="step" type="tc:Step" maxOccurs="unbounded" minOccurs="1"></element>
			<element name="teardown" type="tc:SetupOrTeardown" maxOccurs="1" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="SetupOrTeardown">
		<sequence>
			<element name="sql" type="string" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="Step">
		<sequence>
			<element name="request" type="tc:Request"></element>
			<element name="response" type="tc:Response"></element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>

	<complexType name="Request">
		<sequence>
			<element name="header" type="tc:Header" maxOccurs="unbounded" minOccurs="0"></element>
			<element name="body" type="string" maxOccurs="1" minOccurs="0"></element>
		</sequence>
		<attribute name="method" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="DELETE"></enumeration>
					<enumeration value="GET"></enumeration>
					<enumeration value="POST"></enumeration>
					<enumeration value="PUT"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="uri" type="string" use="required"></attribute>
        <attribute name="contentType" type="string" use="optional" default="application/xml"></attribute>
        <attribute name="accept" type="string" use="optional" default="application/xml" />
	</complexType>

	<complexType name="Response">
		<sequence>
			<element name="header" type="tc:Header" maxOccurs="unbounded" minOccurs="0"></element>
			<element name="body" type="string" maxOccurs="1" minOccurs="0"></element>
		</sequence>
		<attribute name="status" type="int" use="optional" default="200"></attribute>
	</complexType>

	<complexType name="Header">
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="value" type="string" use="required"></attribute>
	</complexType>

</schema>

=== Technology-Hatchery/restsql-test/src/resources/xml/service/testcase/FlatOneToOne/TestDelete_MultiRow_ByQuery.xml
<?xml version="1.0" encoding="UTF-8"?>
<tc:testcase xmlns:tc="http://restsql.org/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://restsql.org/schema ServiceTestCaseDefinition.xsd ">
	<setup>
		<sql>INSERT INTO film (film_id,title,release_year,language_id,rental_duration,rental_rate,replacement_cost) VALUES (5000,'ESCAPE FROM TOMORROW',2011,1,0,0,0)</sql>
		<sql>INSERT INTO film (film_id,title,release_year,language_id,rental_duration,rental_rate,replacement_cost) VALUES (5001,'BLOOD PURPLE',2012,1,0,0,0)</sql>
		<sql>INSERT INTO film (film_id,title,release_year,language_id,rental_duration,rental_rate,replacement_cost) VALUES (5002,'THE DARKENING',2012,1,0,0,0)</sql>
		<sql>INSERT INTO film_rating (film_rating_id,film_id,stars) VALUES (1,5000,5)</sql>
		<sql>INSERT INTO film_rating (film_rating_id,film_id,stars) VALUES (2,5001,1)</sql>
		<sql>INSERT INTO film_rating (film_rating_id,film_id,stars) VALUES (3,5002,1)</sql>
	</setup>
	<step name="execute">
		<request method="DELETE" uri="res/FlatOneToOne?year=2012" />
		<response>
			<body>
<![CDATA[
<writeResponse rowsAffected="2" />
]]>
				</body>
		</response>
	</step>
	<step name="verify">
		<request uri="res/FlatOneToOne?year=2012" method="GET" />
		<response>
			<body>
<![CDATA[
<readResponse>
</readResponse>
]]>
		</body>
		</response>
	</step>
	<step name="verify2">
		<request uri="res/SingleTable_FilmRating" method="GET" />
		<response>
			<body>
<![CDATA[
<readResponse>
	<film_rating film_rating_id="1" film_id="5000" stars="5" />
</readResponse>
]]>
		</body>
		</response>
	</step>
	<teardown>
		<sql>DELETE FROM film_rating</sql>
		<sql>DELETE FROM film WHERE film_id between 5000 and 5500</sql>
	</teardown>
</tc:testcase>

=== Technology-Hatchery/restsql-test/src/resources/xml/service/testcase/DateTime/TestUpdate_ByFormParam.xml
<?xml version="1.0" encoding="UTF-8"?>
<tc:testcase xmlns:tc="http://restsql.org/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://restsql.org/schema ServiceTestCaseDefinition.xsd ">
	<setup>
		<sql>INSERT INTO datetime (id, time, timestamp, date, datetime) VALUES (1000, '16:54:00', '2011-07-23 16:54:00', '2011-07-23', '2011-07-23 16:54:00')</sql>
		<sql>INSERT INTO datetime (id, time, timestamp, date, datetime) VALUES (1000, '8:54:00', '2011-07-23 8:54:00', '2011-07-23', '2011-07-23 8:54:00')</sql>
	</setup>
	<step name="execute">
		<request method="POST" uri="res/DateTime?datetime=2011-07-23%2016:54:00" contentType="application/x-www-form-urlencoded">
			<body>
<![CDATA[
id=1001&time=10:54:00&timestamp=2011-07-22%2010:54:00&date=2011-07-22&datetime=2011-07-22%2010:54:00
]]>
			</body>
		</request>
		<response>
			<body>
<![CDATA[
<writeResponse rowsAffected="1" />
]]>
				</body>
		</response>
	</step>
	<step name="verify">
		<request method="GET" uri="res/DateTime?datetime=2011-07-22%2010:54:00" />
		<response>
			<body>
<![CDATA[
<readResponse>
	<datetime id="1001" time="10:54:00" timestamp="2011-07-22 10:54:00.0" date="2011-07-22" datetime="2011-07-22 10:54:00.0" />
</readResponse>
]]>
			</body>
		</response>
	</step>
	<teardown>
		<sql>DELETE FROM datetime</sql>
	</teardown>
</tc:testcase>

=== Technology-Hatchery/restsql-test/src/resources/xml/service/testcase/SingleTable/TestUpdate_SingleRow_ByPathAndFormParam.xml
<?xml version="1.0" encoding="UTF-8"?>
<tc:testcase xmlns:tc="http://restsql.org/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://restsql.org/schema ServiceTestCaseDefinition.xsd ">
	<setup>
		<sql>INSERT INTO actor (actor_id,first_name,last_name) VALUES (1000,'John','Smith')</sql>
	</setup>
	<step name="execute">
		<request method="PUT" uri="res/SingleTable/1000" contentType="application/x-www-form-urlencoded">
			<body>
<![CDATA[
first_name=_Jack&last_name=Daniels
]]>
			</body>
		</request>
		<response>
			<body>
<![CDATA[
<writeResponse rowsAffected="1" />
]]>
			</body>
		</response>
	</step>

	<step name="verify">
		<request method="GET" uri="res/SingleTable/1000" />
		<response>
			<body>
<![CDATA[
<readResponse>
	<actor actor_id="1000" first_name="_Jack" last_name="Daniels" />
</readResponse>
]]>
			</body>
		</response>
	</step>

	<teardown>
		<sql>DELETE FROM actor where actor_id between 1000 and 1100</sql>
	</teardown>
</tc:testcase>

=== Technology-Hatchery/restsql-test/src/resources/xml/service/testcase/SingleTable/TestDelete_MultiRow_ByBody.xml
<?xml version="1.0" encoding="UTF-8"?>
<tc:testcase xmlns:tc="http://restsql.org/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://restsql.org/schema ../ServiceTestCaseDefinition.xsd ">
	<setup>
		<sql>INSERT INTO actor (actor_id,first_name,last_name) VALUES (1000,'_Jack','Smith')</sql>
		<sql>INSERT INTO actor (actor_id,first_name,last_name) VALUES (1001,'_Jack','Johnson')</sql>
	</setup>
	<step name="execute">
		<request method="DELETE" uri="res/SingleTable">
			<body>
<![CDATA[
<request>
	<actor id="1000" />
	<actor id="1001" />
</request>
]]>
			</body>
		</request>
		<response>
			<body>
<![CDATA[
<writeResponse rowsAffected="2" />
]]>
				</body>
		</response>
	</step>
	<step name="verify">
		<request uri="res/SingleTable?first_name=_Jack" method="GET" />
		<response>
			<body>
<![CDATA[
<readResponse />
]]>
		</body>
		</response>
	</step>
	<teardown>
		<sql>DELETE FROM actor where actor_id between 1000 and 1100</sql>
	</teardown>
</tc:testcase>

=== Technology-Hatchery/restsql-test/src/resources/xml/service/testcase/SingleTable/TestInsert_SingleRow_ByBody_TriggerException.xml
<?xml version="1.0" encoding="UTF-8"?>
<tc:testcase xmlns:tc="http://restsql.org/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://restsql.org/schema ../ServiceTestCaseDefinition.xsd ">
	<step name="execute">
		<request method="POST" uri="res/SingleTable">
			<body>
<![CDATA[
<request>
	<actor id="1000" first_name="A first name that is too long for the domain rule" surname="Daniels" />
</request>
]]>
		</body>
		</request>
		<response status="400">
		<body>First name length must be less or equal to 25 characters</body>
		</response>
	</step>

	<teardown>
		<sql>DELETE FROM actor where actor_id between 1000 and 1100</sql>
	</teardown>
</tc:testcase>

=== Technology-Hatchery/restsql-test/src/resources/xml/service/testcase/Security/TestInsert_Authorized.xml
<?xml version="1.0" encoding="UTF-8"?>
<tc:testcase xmlns:tc="http://restsql.org/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://restsql.org/schema ServiceTestCaseDefinition.xsd ">
	<step name="execute">
		<request method="POST" uri="res/SingleTable" contentType="application/x-www-form-urlencoded"
			user="limited" password="limited">
			<body>
<![CDATA[
id=1000&first_name=_Jack&surname=Daniels
]]>
			</body>
		</request>
		<response>
			<body>
<![CDATA[
<writeResponse rowsAffected="1" />
]]>
			</body>
		</response>
	</step>

	<step name="verify">
		<request method="GET" uri="res/SingleTable?first_name=_Jack" />
		<response>
			<body>
<![CDATA[
<readResponse>
	<actor id="1000" first_name="_Jack" surname="Daniels" />
</readResponse>
]]>
			</body>
		</response>
	</step>

	<teardown>
		<sql>DELETE FROM actor where actor_id between 1000 and 1100</sql>
	</teardown>
</tc:testcase>

=== Technology-Hatchery/restsql-test/src/resources/xml/service/testcase/FlatOneToOneMulti/TestDelete_SingleRow_ByPath.xml
<?xml version="1.0" encoding="UTF-8"?>
<tc:testcase xmlns:tc="http://restsql.org/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://restsql.org/schema ../ServiceTestCaseDefinition.xsd ">
	<setup>
		<sql>INSERT INTO film (film_id,title,release_year,language_id,rental_duration,rental_rate,replacement_cost) VALUES (5000,'ESCAPE FROM TOMORROW',2011,1,0,0,0)</sql>
		<sql>INSERT INTO film (film_id,title,release_year,language_id,rental_duration,rental_rate,replacement_cost) VALUES (5001,'BLOOD PURPLE',2012,1,0,0,0)</sql>
		<sql>INSERT INTO film (film_id,title,release_year,language_id,rental_duration,rental_rate,replacement_cost) VALUES (5002,'THE DARKENING',2012,1,0,0,0)</sql>
		<sql>INSERT INTO film_comment (film_id,comment) VALUES (5000,'not so bad')</sql>
		<sql>INSERT INTO film_comment (film_id,comment) VALUES (5001,'loved it')</sql>
		<sql>INSERT INTO film_comment (film_id,comment) VALUES (5002,'I laughed, I cried')</sql>
		<sql>INSERT INTO film_genre (film_id,genre) VALUES (5000,'SCIENCE FICTION')</sql>
		<sql>INSERT INTO film_genre (film_id,genre) VALUES (5001,'HORROR')</sql>
		<sql>INSERT INTO film_genre (film_id,genre) VALUES (5002,'HORROR')</sql>
		<sql>INSERT INTO film_origin (film_id,city,country) VALUES (5000,'New York', 'USA')</sql>
		<sql>INSERT INTO film_origin (film_id,city,country) VALUES (5001,'Hollywood', 'USA')</sql>
		<sql>INSERT INTO film_origin (film_id,city,country) VALUES (5002,'Hollywood', 'USA')</sql>
	</setup>
	<step name="execute">
		<request method="DELETE" uri="res/FlatOneToOneMulti/5000" />
		<response>
			<body>
<![CDATA[
<writeResponse rowsAffected="4" />
]]>
				</body>
		</response>
	</step>
	<step name="verify">
		<request method="GET" uri="res/FlatOneToOneMulti?year=2012" />
		<response>
			<body>
<![CDATA[
<readResponse>
	<film film_id="5001" title="BLOOD PURPLE" year="2012" language_id="1" comment="loved it" genre="HORROR" city="Hollywood" country="USA" />
	<film film_id="5002" title="THE DARKENING" year="2012" language_id="1" comment="I laughed, I cried" genre="HORROR" city="Hollywood" country="USA" />
</readResponse>
]]>
			</body>
		</response>
	</step>
	<teardown>
		<sql>DELETE FROM film_comment</sql>
		<sql>DELETE FROM film_genre</sql>
		<sql>DELETE FROM film_origin</sql>
		<sql>DELETE FROM film WHERE film_id between 5000 and 5500</sql>
	</teardown>
</tc:testcase>

=== Technology-Hatchery/restsql-test/src/resources/xml/service/testcase/SingleTable/TestDelete_MultiRow_ByQuery.xml
<?xml version="1.0" encoding="UTF-8"?>
<tc:testcase xmlns:tc="http://restsql.org/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://restsql.org/schema ServiceTestCaseDefinition.xsd ">
	<setup>
		<sql>INSERT INTO actor (actor_id,first_name,last_name) VALUES (1000,'John','_Smith')</sql>
		<sql>INSERT INTO actor (actor_id,first_name,last_name) VALUES (1001,'Joseph','_Smith')</sql>
	</setup>
	<step name="execute">
		<request method="DELETE" uri="res/SingleTable?surname=_Smith" />
		<response>
			<body>
<![CDATA[
<writeResponse rowsAffected="2" />
]]>
		</body>
		</response>
	</step>
	<step name="verify">
		<request uri="res/SingleTable?surname=_Smith" method="GET" />
		<response>
			<body>
<![CDATA[
<readResponse>
</readResponse>
]]>
		</body>
		</response>
	</step>
	<teardown>
		<sql>DELETE FROM actor where actor_id between 1000 and 1100</sql>
	</teardown>
</tc:testcase>
