=== Technology-Hatchery/restsql-test/src/resources/xml/service/testcase/ServiceTestCaseDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://restsql.org/schema" elementFormDefault="unqualified"
	xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tc="http://restsql.org/schema">

	<element name="testcase" type="tc:ServiceTestCaseDefinition"></element>

	<complexType name="ServiceTestCaseDefinition">
		<sequence>
			<element name="setup" type="tc:SetupOrTeardown" maxOccurs="1" minOccurs="0"></element>
			<element name="step" type="tc:Step" maxOccurs="unbounded" minOccurs="1"></element>
			<element name="teardown" type="tc:SetupOrTeardown" maxOccurs="1" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="SetupOrTeardown">
		<sequence>
			<element name="sql" type="string" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="Step">
		<sequence>
			<element name="request" type="tc:Request"></element>
			<element name="response" type="tc:Response"></element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>

	<complexType name="Request">
		<sequence>
			<element name="header" type="tc:Header" maxOccurs="unbounded" minOccurs="0"></element>
			<element name="body" type="string" maxOccurs="1" minOccurs="0"></element>
		</sequence>
		<attribute name="method" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="DELETE"></enumeration>
					<enumeration value="GET"></enumeration>
					<enumeration value="POST"></enumeration>
					<enumeration value="PUT"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="uri" type="string" use="required"></attribute>
        <attribute name="contentType" type="string" use="optional" default="application/xml"></attribute>
        <attribute name="accept" type="string" use="optional" default="application/xml" />
	</complexType>

	<complexType name="Response">
		<sequence>
			<element name="header" type="tc:Header" maxOccurs="unbounded" minOccurs="0"></element>
			<element name="body" type="string" maxOccurs="1" minOccurs="0"></element>
		</sequence>
		<attribute name="status" type="int" use="optional" default="200"></attribute>
	</complexType>

	<complexType name="Header">
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="value" type="string" use="required"></attribute>
	</complexType>

</schema>

=== Technology-Hatchery/restsql-test/src/resources/xml/service/testcase/Security/TestDelete_Unauthorized.xml
<?xml version="1.0" encoding="UTF-8"?>
<tc:testcase xmlns:tc="http://restsql.org/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://restsql.org/schema ServiceTestCaseDefinition.xsd ">
	<setup>
		<sql>INSERT INTO actor (actor_id,first_name,last_name) VALUES (1000,'John','Smith')</sql>
	</setup>
	<step name="execute">
		<request method="DELETE" uri="res/SingleTable/1000" user="limited" password="limited" />
		<response status="403" />
	</step>
	<teardown>
		<sql>DELETE FROM actor where actor_id between 1000 and 1100</sql>
	</teardown>
</tc:testcase>

=== Technology-Hatchery/restsql-test/src/resources/xml/service/testcase/ReadOnlyColumns/TestDelete_SingleTable_MultiRow_ByQuery.xml
<?xml version="1.0" encoding="UTF-8"?>
<tc:testcase xmlns:tc="http://restsql.org/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://restsql.org/schema ServiceTestCaseDefinition.xsd ">
	<setup>
		<sql>INSERT INTO actor (actor_id,first_name,last_name,last_update) VALUES (1000,'John','Sm','2012-02-15 04:34:33.0')</sql>
		<sql>INSERT INTO actor (actor_id,first_name,last_name,last_update) VALUES (1001,'Sally','Sm','2012-02-15 04:34:33.0')</sql>
	</setup>
	<step name="execute">
		<request method="DELETE" uri="res/SingleTableFuncCols?surname_length=2" />
		<response status="400">
			<body>
<![CDATA[
Column surname_length is read-only and may not be a query parameter or updated
]]>
		</body>
		</response>
	</step>
	<teardown>
		<sql>DELETE FROM actor where actor_id between 1000 and 1100</sql>
	</teardown>
</tc:testcase>
